name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
  deploy_to_development:
    name: Deploy to Development
    runs-on: ubuntu-latest
    environment:
      name: development # This links to your GitHub Environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Application
        run: echo "Deploying to development..."

      - name: Use Secret
        run: echo "The secret is ${{ secrets.API_KEY }}"

  deploy_to_production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment:
      name: production # This links to your GitHub Environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Application
        run: echo "Deploying to Production..."

      - name: Use Secret
        run: echo "The secret is ${{ secrets.API_KEY }}"

