name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'development' }}  # This links to your GitHub Environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Application
        run: echo "Deploying to Production..."

      - name: Use Secret
        run: echo "The secret is ${{ secrets.API_KEY }}"

