name: Use Github App
on:
  workflow_dispatch:

jobs:
  checkout-other-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.GH_APPLICATION_ID }}
          private-key: ${{ secrets.GH_APPLICATION_KEY }}

      - uses: actions/checkout@v4.2.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: rameshk553/test_context_options
      
